- name: Install Grafana
  ansible.builtin.package:
    name:
      - www/grafana9
    state: present

- name: TAILSCALE SERVE GRAFANA
  ansible.builtin.command: "/usr/local/bin/tailscale serve / proxy 3000"
  changed_when: false

- name: GRAFANA CONFIGURATION
  ansible.builtin.template:
    src: ./usr/local/etc/grafana/grafana.ini
    dest: /usr/local/etc/grafana/grafana.ini
    owner: root
    group: wheel
    mode: 0644
  register: grafana_configuration

- name: Enable and start Grafana
  ansible.builtin.service:
    name: grafana
    state: restarted
    enabled: true
  when: grafana_configuration.changed
